name: "Check PR Title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  # The PR trigger config could trigger 2-3 builds at the same time based on user action,
  # we only need one to run to avoid unnecessary build time.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-pr-title:
    uses: springlabs/gh-workflows/.github/workflows/pr-title.yml@main
